service: max-spatial-service-overlap
frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-2
  runtime: python3.7
  lambdaHashingVersion: 20201221
  
functions:
  find_max:
    handler: src/handler.get_max_pizza_overlap 
    layers:
      - arn:aws:lambda:eu-west-2:142628438157:layer:AWSLambda-Python37-SciPy1x:113
    events:
      - http:
          path: /api/max_pizza_overlap
          method: post
